sortname: name
sortorder: asc
columnNames:
  - activerecord.attributes.project.name
  - activerecord.attributes.project.start_date
  - activerecord.attributes.project.end_date
columns:
  - name: name
    index: name
    width: 40
  - name: start_date
    index: start_date
    width: 30
  - name: end_date
    index: end_date
    width: 30
