javascripts:
- base:
  - jquery-1.3.2
  - jquery.domec
  - jquery-ui-1.7.2.custom.min
  - application
- wysiwyg:
  - jHtmlArea-0.7.0
  - jHtmlArea.ColorPickerMenu-0.7.0
- grid:
  - jqgrid/jquery.layout
  - jqgrid/jquery.tablednd
  - jqgrid/jquery.contextmenu
  - jqgrid/src/grid.base
  - jqgrid/src/jquery.fmatter
  - jqgrid/src/grid.custom
  - jqgrid/src/grid.common
  - jqgrid/src/grid.formedit
  - jqgrid/src/jquery.searchFilter
  - jqgrid/src/grid.inlinedit
  - jqgrid/src/grid.celledit
  - jqgrid/src/grid.subgrid
  - jqgrid/src/grid.treegrid
  - jqgrid/src/grid.import
  - jqgrid/src/JsonXml
  - jqgrid/src/grid.setcolumns
  - jqgrid/src/grid.postext
  - jqgrid/src/grid.tbltogrid
  - jqgrid/src/grid.jqueryui
stylesheets:
- screen:
  - blueprint/screen
  - jquery-ui-1.7.2.start
  - ui.jqgrid
  - screen
- admin_screen:
  - blueprint/screen
  - jquery-ui-1.7.2.black-tie
  - ui.jqgrid
  - screen
- print:
  - blueprint/print
  - print
- ie:
  - blueprint/ie
  - ie
- wysiwyg:
  - jHtmlArea
  - jHtmlArea.ColorPickerMenu

