javascripts:
- base:
  - jquery-1.3.2
  - jquery.domec
  - jquery-ui-1.7.2.custom.min
  - application
- wysiwyg:
  - jHtmlArea-0.7.0
  - jHtmlArea.ColorPickerMenu-0.7.0
- grid:
  - jqgrid/jquery.layout.js
  - jqgrid/i18n/grid.locale-#{locale}.js
  - jqgrid/jquery.jqGrid.min
  - jqgrid/jquery.tablednd.js
  - jqgrid/jquery.contextmenu.js
- grid_debug:
  - jqgrid/jquery.layout.js
  - jqgrid/i18n/grid.locale-#{locale}.js
  - jqgrid/src/grid.base.js
  - jqgrid/src/jquery.fmatter.js
  - jqgrid/src/grid.custom.js
  - jqgrid/src/grid.common.js
  - jqgrid/src/grid.formedit.js
  - jqgrid/src/jquery.searchFilter.js
  - jqgrid/src/grid.inlinedit.js
  - jqgrid/src/grid.celledit.js
  - jqgrid/src/grid.subgrid.js
  - jqgrid/src/grid.treegrid.js
  - jqgrid/src/grid.import.js
  - jqgrid/src/JsonXml.js
  - jqgrid/src/grid.setcolumns.js
  - jqgrid/src/grid.postext.js
  - jqgrid/src/grid.tbltogrid.js
  - jqgrid/src/grid.jqueryui.js
  - jqgrid/jquery.tablednd.js
  - jqgrid/jquery.contextmenu.js
stylesheets:
- screen:
  - screen
  - jquery-ui-1.7.2.start
  - ui.jqgrid
  - my-screen
- admin_screen:
  - screen
  - jquery-ui-1.7.2.black-tie
  - ui.jqgrid
  - my-screen
- print:
  - print
  - my-print
- ie:
  - ie
  - my-ie
- wysiwyg:
  - jHtmlArea
  - jHtmlArea.ColorPickerMenu

